---
- hosts: appgroup
  remote_user: root
  tasks:
  - name: ensure nginx is at the latest version
    yum:
      name: epel-release
      state: latest
  - name: nginx 2/2
    yum:
      name: nginx
      state: latest
...

